# Generated by Django 5.1.6 on 2025-02-24 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_message_file_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
